- name: Crear backup
  hosts: "{{ host_ip }}"
  become: true
  vars:
    ansible_user: ubuntu

  tasks:
    - name: Instalar ACL en EC2
      become: yes
      ansible.builtin.apt:
        name: acl
        state: present
        update_cache: yes

    - name: Crear usuario git
      ansible.builtin.user:
        name: git
        state: present
        create_home: no

    - name: Dar permisos al usuario git
      ansible.posix.acl:
        path: "{{ item }}"
        entity: git
        etype: user
        permissions: rwx
        state: present
        recursive: true
      loop:
        - /var/lib/gogs/data
        - /var/lib/gogs/backup

    - name: Ejecutar Gogs backup
      shell: docker exec -u git gogs ./gogs backup

    - name: Encontrar backup
      shell: "ls -t /var/lib/gogs/backup/*.zip | head -n 1"
      register: latest_backup
      changed_when: false

    - name: Copiar backup en el agente
      fetch:
        src: "{{ latest_backup.stdout }}"
        dest: "../backup/"
        flat: yes
