- name: Crear backup
  hosts: "{{ host_ip }}"
  become: true
  vars:
    ansible_user: ubuntu

  tasks:
    - name: Ejecutar Gogs backup
      docker_container_exec:
        container: gogs
        command: ./gogs backup

    - name: Encontrar backup
      shell: "ls -t /var/lib/gogs/backup/*.zip | head -n 1"
      register: latest_backup
      changed_when: false

    - name: Copiar backup en el agente
      fetch:
        src: "{{ latest_backup.stdout }}"
        dest: "../backup/"
        flat: yes
