- name: Restaurar backup
  hosts: "{{ host_ip }}"
  become: true
  vars:
    ansible_user: ubuntu

  tasks:
    # - name: Instalar ACL en VM
    #   become: yes
    #   ansible.builtin.apt:
    #     name: acl
    #     state: present
    #     update_cache: yes

    # - name: Crear usuario git
    #   ansible.builtin.user:
    #     name: git
    #     state: present
    #     create_home: no

    # - name: Dar permisos al usuario git
    #   ansible.posix.acl:
    #     path: "{{ item }}"
    #     entity: git
    #     etype: user
    #     permissions: rwx
    #     state: present
    #     recursive: true
    #   loop:
    #     - /var/lib/gogs/data
    #     - /var/lib/gogs/backup

    - name: Dar permisos de escritura a los directorios
      shell: "docker exec gogs chmod 777 {{ item }}"
      loop:
        - /data
        - /backup

    - name: Encontrar backup
      shell: "ls -t ../backup/*.zip | head -n 1"
      register: latest_backup
      changed_when: false

    - name: Copiar archivo de backup
      copy:
        src: "{{ latest_backup.stdout }}"
        dest: "/var/lib/gogs/backup/gogs-backup.zip"

    - name: Restore Gogs inside Docker
      shell: docker exec -u root gogs ./gogs restore --from="/backup/gogs-backup.zip" --config=/data/gogs/conf/app.ini
